replicaCount: 1

secretName: azure-devops-agent-secret

image:
  repository: dockeragent
  pullPolicy: IfNotPresent
  tag: "latest"

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false 
  runAsNonRoot: true
  runAsUser: 1000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

affinity: {}
