replicaCount: 1

secretName: azure-devops-agent-secret

image:
  repository: dockeragent
  pullPolicy: IfNotPresent
  tag: "latest"

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false 
  runAsNonRoot: true
  runAsUser: 1000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

affinity: {}

secret:
  secretName: azure-devops-agent-secret
  environment:
    AZP_URL: foo-url
    AZP_TOKEN: foo-token
    AZP_POOL: foo-pool
    AZP_AGENT_NAME: foo-agent
