apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "self-hosted-agent.fullname" . }}
  labels:
    {{- include "self-hosted-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "self-hosted-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "self-hosted-agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: AZP_URL
            valueFrom:
              secretKeyRef:
                name: azure-devops-agent-secret
                key: AZP_URL
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azure-devops-agent-secret
                key: AZP_TOKEN
          - name: AZP_POOL
            valueFrom:
              secretKeyRef:
                name: azure-devops-agent-secret
                key: AZP_POOL
          - name: AZP_AGENT_NAME
            valueFrom:
              secretKeyRef:
                name: azure-devops-agent-secret
                key: AZP_AGENT_NAME
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
