{{ if .Values.secret.environment }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.secretName }}
type: Opaque
data: 
{{- range $key, $value := .Values.secret.environment  }}
  {{- if not $value }}
    {{- required (printf "A valid %s is required." $key) $value }}
  {{- else }}
    {{ $key | indent 2 }}: {{ $value | b64enc }}
  {{- end}}
{{- end}}
{{- end}}