name: build the docker image, scan vunerabilities, lint and test the Helm chart

on:
  push:

jobs:
  build:
    name: Build, scan, lint, and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build docker image
        run: docker build --progress=plain --no-cache -t dockeragent:latest .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'dockeragent:latest'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'

      - name: Setup Helm Unit Tests
        uses: d3adb5/helm-unittest-action@v1

      - name: Helm Lint
        run: helm lint charts/self-hosted-agent

      - name: Helm Unit test
        run: helm unittest -3 charts/self-hosted-agent

